name: Build and Publish Docker Image

on:
  push:
    branches:
      - main  # Defina a branch que acionará o workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo dckr_pat_gEaPXJwSNT6ykNwvNSpI-p3HM-4 | docker login -u gabrielralphi --password-stdin

      - name: Build and tag Docker image
        run: docker build -t dockerimage .

      - name: Push Docker image
        run: docker push dockerimage