name: Build and Publish Docker Image

on:
  push:
    branches:
      - main  # Defina a branch que acionará o workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: docker login -u gabrielralphi -p dckr_pat_ZSU4GyU-xJQG_QcpTSaILhDepFs

      - name: Build and tag Docker image
        run: docker build -t dockerimage .

      - name: Tag Docker image
        run: docker tag dockerimage gabrielralphi/dockerimage

      - name: Push Docker image
        run: docker push gabrielralphi/dockerimage